name: Unity Build Windows

on:
  push:
    branches:
      - main  # mainブランチへのpush時にビルドを実行

jobs:
  build:
    runs-on: ubuntu-latest  # または windows-latest でも実行可能

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Unity
      uses: game-ci/unity-builder@v2
      with:
        version: 2021.3.12f1  # 使用するUnityのバージョンを指定
        targetPlatform: StandaloneWindows64  # ビルドターゲットを指定（Windows用）
        projectPath: ${{ github.workspace }}  # プロジェクトパス
        buildName: "MyGameBuild"  # ビルド名を指定
        buildTarget: StandaloneWindows64  # Windows用のビルドターゲット
        buildPath: ${{ github.workspace }}/Build/Windows  # 出力先のパス
        unityLicense: ${{ secrets.UNITY_LICENSE }}  # Unityのライセンス（後述）

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WindowsBuild
        path: ${{ github.workspace }}/Build/Windows
